### ISSUE TITLE
Error in Installation

### ISSUE THREAD

**Issue by imranhhk** [DevelopersPL/otshosting-provisioning#1]
Ubuntu 14.04 Error:
https://otland.net/threads/simple-all-in-one-from-nothing-to-a-fully-working-dedicated-server-on-ubuntu.212117/page-4#post-2228720
![image](https://cloud.githubusercontent.com/assets/6464240/8334919/843319c0-1a68-11e5-9c10-2e54be3d4855.png)

Ubuntu 15.04 Error:
https://otland.net/threads/simple-all-in-one-from-nothing-to-a-fully-working-dedicated-server-on-ubuntu.212117/page-4#post-2254581

**Comment by DSpeichert** [comment]
How much memory does your system have? Are you sure it's not exhausted?
I just tried running the script on a fresh Ubuntu 14.04 install and it worked.

**Comment by imranhhk** [comment]
The system has 32 GB RAM. I purchased it from SoYouStart.com:
1. Did a fresh install of Ubuntu 14.04
2. Restarted the server (just to be safe)
3. Ran the commands and got this error:
http://pastebin.com/SYasmGLZ

I actually have the system installed on another server with the exact same specs so I'm not sure why it's not working this time.

**Comment by DSpeichert** [comment]
I don't think we can fix that in this case. It seems like your compiler is just crashing for no reason and I cannot reproduce that. I suggest you reinstall all packages after you install the OS in SYS panel and when you install the OS, select an option to use distro's kernel.

**Comment by Nu77** [comment]
@imranhhk @DSpeichert 
otland/forgottenserver#1404

**Comment by imranhhk** [comment]
Update:
Although it shows an error message in the installation, everything is still installed correctly! :+1: 

There is only an error in compiling the tfs during the automatic process, but you can easily replace the Cmakelists.txt and src files and compile afterwards.
