### ISSUE TITLE
Update in otland/forgottenserver broke the task tfs.yml (config.lua renamed to config.lua.dist)

### ISSUE THREAD

**Issue by Znote** [DevelopersPL/otshosting-provisioning#10]
In this update:
https://github.com/otland/forgottenserver/commit/20df00b63c8a98e082d425fa84ba7688f58a3406

config.lua was renamed to config.lua.dist. 

Which means these steps will fail:
https://github.com/DevelopersPL/otshosting-provisioning/blob/master/tasks/tfs.yml#L35-L39

**Comment by DSpeichert** [comment]
Fixes in 55fe9736155579025ccbad202ab2434b2a2f9f57 & 2e787e7ed4bfcdb8f10ebf4c87049b9cdb6818d5
