### ISSUE TITLE
DB during installation

### ISSUE THREAD

**Issue by tresvitae** [DevelopersPL/otshosting-provisioning#13]
Hi I've problem during installation otshosting on my fresh ubuntu server 18.3. In Task Import database for TFS i've got fatal: ERROR 1062 (23000) at  line 342: Duplicate entry 'db_version' for key 'PRIMARY'\n" to retry, use: --limit @/srv/otshosting-provisioning/local.retry.  SO i did it and add that command to the last "install" command and error still exist.
![1123](https://user-images.githubusercontent.com/30234663/69082552-9a3b8c80-0a40-11ea-8547-4e64fb5dccf4.png)
 
any suggestion?

**Comment by DSpeichert** [comment]
That means your database isn't empty and you're trying to import the schema there second time.

You either need to wipe out the database and start from scratch or skip this step of importing the schema if you want to retain what you already have.
