### ISSUE TITLE
cant make it work

### ISSUE THREAD

**Issue by murilow1** [DevelopersPL/otshosting-provisioning#2]
http://imgur.com/a/04XMQ
still with this error for days..

things i've tried:
re-install ubuntu 15.10
rm -rf /srv/otshosting-provisioning and exec the last command again
curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin 
check universe, multiverse and restricted
and others things...

im using ubuntu 15.10 powered by vmware with 2gb ram...

**Comment by DSpeichert** [comment]
The error message is clear, you have to do:

```
apt-get install aptitude
```

**Comment by murilow1** [comment]
thank you, works fine now, this command shouldnt be default in the code? since aptitude dont come with ubuntu...

**Comment by DSpeichert** [comment]
It does in cloud-image, which is what I always use. I updated README.md to make it clear (2fd31ec1347ff7510f507d6b8c6356ef35aed4f1)

**Comment by murilow1** [comment]
Fine, thanks for the great job!
