### ISSUE TITLE
Doubt in command

### ISSUE THREAD

**Issue by luanluciano93** [DevelopersPL/otshosting-provisioning#20]
`ansible-pull -i localhost, -U https://github.com/DevelopersPL/otshosting-provisioning.git -d /srv/otshosting-provisioning --purge -t default`

Wouldn't it be necessary to install ansive?

```
sudo apt install ansible -y
sudo ansible-pull -i localhost, -U https://github.com/DevelopersPL/otshosting-provisioning.git -d /srv/otshosting-provisioning --purge -t default`
```

**Comment by DSpeichert** [comment]
Yes, the README.md lists all three commands.
