### ISSUE TITLE
library question

### ISSUE THREAD

**Issue by luanluciano93** [DevelopersPL/otshosting-provisioning#21]
https://github.com/DevelopersPL/otshosting-provisioning/blob/7fd261d989fe95fc07b7e45849c808a397f4fab1/tasks/tfs.yml#L15

in the TFS compilation procedure there is no such lib, is it really necessary? What is your function?
https://github.com/otland/forgottenserver/wiki/Compiling-on-Ubuntu

**Comment by DSpeichert** [comment]
It can be used instead of LuaJIT.
