### ISSUE TITLE
Doubt journald

### ISSUE THREAD

**Issue by luanluciano93** [DevelopersPL/otshosting-provisioning#23]
Is journald only used to save server logs? It wouldn't be easier to use an  ./tfs >> /home/otsmanager/forgottenserver/test.log &???

**Comment by luanluciano93** [comment]
?

**Comment by DSpeichert** [comment]
No, journald is used for almost all logs on the system and has many modern features.

Easier? Maybe. It might be easier to not use Ansible too.

**Comment by luanluciano93** [comment]
thanks
