### ISSUE TITLE
After last command it shows error

### ISSUE THREAD

**Issue by chytron** [DevelopersPL/otshosting-provisioning#3]
Hello.
I want to start my adventure (heh) with opentibia. I found your guide on the internet and it seemed to be very simple. Now I know it's not so simple, because I stumbled upon many problems.
Alright. I tried to install this on Ubuntu 15.04 Server, Ubuntu 15.10 Server and Ubuntu 16.04 Server, but always I have this one problem, and I don't know how to fix it.
After writing last command it shows:

```
Starting ansible-pull at 2015-06-24 01:21:10
localhost | success >> {
    "after": "(manyoflettersanddigits)",
    "before": null,
    "changed": true
```

```
And nothing happens.
After ~10 minutes it shows
EXT4-fs (sda2): unable to read superblock
FAT-fs (sda2): bogus number of reserved sectors
qnx4: no qnx4 filesystem (no root dir).
ufs: you didn't specify the type of your ufs filesystem
mount -t ufs -o ufstype=sun|sunx64|44bsd|ufs2|5xbsd|old|hp|nextstep-cd|openstep ...
>>>WARNING<<< Wrong ufstype may corrupt your filesystem, default is ufstype=old
```

I'm running on AMD64.

**Comment by chytron** [comment]
Just as I thought, no help received.

**Comment by DSpeichert** [comment]
It looks like a hardware/OS-level problem and is not related to our playbook.
