### ISSUE TITLE
Line 1-3/3 END. What is that?

### ISSUE THREAD

**Issue by chytron** [DevelopersPL/otshosting-provisioning#7]
Hello

I have problem. After installation i logged on otsmanager and I can't do anything.
It shows lines 1-3/3 (END) and blinking writing line at the end.
During the installation, there were no errors.

I have Ubuntu 16.04.

**Comment by DSpeichert** [comment]
The viewer opens in non-batch mode. Press q.

**Comment by jtsamas** [comment]
@DSpeichert Thanks. this helped me

**Comment by BXYHT** [comment]
thanks again

**Comment by Ivannumberone** [comment]
и еще раз спасибо)

**Comment by fligende** [comment]
И еще раз спасибо )))
