### ISSUE TITLE
Install php-fpm

### ISSUE THREAD

**Issue by vankk** [DevelopersPL/otshosting-provisioning#9]
Running in Ubuntu 16.04.1 LTS

Running the command
`sudo ansible-pull -i localhost, -U https://github.com/DevelopersPL/otshosting-provisioning.git -d /srv/otshosting-provisioning`

And I'm getting this error

> TASK [include] *****************************************************************
> included: /srv/otshosting-provisioning/tasks/php7.0-fpm.yml for localhost
> 
> TASK [Install php-fpm] *********************************************************
> failed: [localhost] => (item=[u'php-fpm', u'php-apcu', u'php-mysqlnd', u'php-curl', u'php-xml', u'php-mbstring', u'php-gettext', u'composer']) => {"cache_update_time": 0, "cache_updated": false, "failed": true, "item": ["php-fpm", "php-apcu", "php-mysqlnd", "php-curl", "php-xml", "php-mbstring", "php-gettext", "composer"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"   install 'php-fpm' 'php-apcu' 'php-mysqlnd' 'php-curl' 'php-xml' 'php-mbstring' 'php-gettext' 'composer'' failed: E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.\n", "stderr": "E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n composer : Depends: php-symfony-console (>= 2.5) but it is not going to be installed\n            Depends: php-symfony-filesystem (>= 2.5) but it is not going to be installed\n            Depends: php-symfony-finder (>= 2.4) but it is not going to be installed\n            Depends: php-symfony-process (>= 2.4) but it is not going to be installed\n            Depends: php-json-schema (>= 1.6) but it is not going to be installed\n            Depends: php-json-schema (< 2~~) but it is not going to be installed\n            Depends: php-composer-spdx-licenses (>= 1.0) but it is not going to be installed\n            Depends: php-composer-spdx-licenses (< 2~~) but it is not going to be installed\n            Depends: php-composer-semver (>= 1.0) but it is not going to be installed\n            Depends: php-composer-semver (< 2~~) but it is not going to be installed\n            Depends: jsonlint (>= 1.4) but it is not going to be installed\n            Depends: jsonlint (< 2~~) but it is not going to be installed\n            Depends: php-cli-prompt (>= 1.0) but it is not going to be installed\n            Depends: php-cli-prompt (< 2~~) but it is not going to be installed\n php-common : Breaks: php-apcu (< 5.1.3+4.0.10-2~) but 5.1.3+4.0.10-1build1 is to be installed\n php-gettext : Depends: php-pear but it is not going to be installed\n php-mbstring : Depends: php7.0-mbstring but it is not going to be installed\n php-xml : Depends: php7.0-xml but it is not going to be installed\n php7.0-mysql : Depends: php7.0-common (= 7.0.8-0ubuntu0.16.04.2) but 7.0.9-1+deb.sury.org~wily+1 is to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " composer : Depends: php-symfony-console (>= 2.5) but it is not going to be installed", "            Depends: php-symfony-filesystem (>= 2.5) but it is not going to be installed", "            Depends: php-symfony-finder (>= 2.4) but it is not going to be installed", "            Depends: php-symfony-process (>= 2.4) but it is not going to be installed", "            Depends: php-json-schema (>= 1.6) but it is not going to be installed", "            Depends: php-json-schema (< 2~~) but it is not going to be installed", "            Depends: php-composer-spdx-licenses (>= 1.0) but it is not going to be installed", "            Depends: php-composer-spdx-licenses (< 2~~) but it is not going to be installed", "            Depends: php-composer-semver (>= 1.0) but it is not going to be installed", "            Depends: php-composer-semver (< 2~~) but it is not going to be installed", "            Depends: jsonlint (>= 1.4) but it is not going to be installed", "            Depends: jsonlint (< 2~~) but it is not going to be installed", "            Depends: php-cli-prompt (>= 1.0) but it is not going to be installed", "            Depends: php-cli-prompt (< 2~~) but it is not going to be installed", " php-common : Breaks: php-apcu (< 5.1.3+4.0.10-2~) but 5.1.3+4.0.10-1build1 is to be installed", " php-gettext : Depends: php-pear but it is not going to be installed", " php-mbstring : Depends: php7.0-mbstring but it is not going to be installed", " php-xml : Depends: php7.0-xml but it is not going to be installed", " php7.0-mysql : Depends: php7.0-common (= 7.0.8-0ubuntu0.16.04.2) but 7.0.9-1+deb.sury.org~wily+1 is to be installed"]}
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=39   changed=7    unreachable=0    failed=1
> 
> root@158:/usr/local/bin#

**Comment by DSpeichert** [comment]
We are using a Ubuntu 16.04 cloud image to perform the installation all the time and it works for us. Are you sure you have proper (official) apt mirrors set up and they are up to date?
